export const District = [
  {
    label: "Thành phố Long Xuyên",
    path_with_type: "Thành phố Long Xuyên, Tỉnh An Giang",
    code: "883",
    parent_code: "89",
  },
  {
    label: "Thành phố Châu Đốc",
    path_with_type: "Thành phố Châu Đốc, Tỉnh An Giang",
    code: "884",
    parent_code: "89",
  },
  {
    label: "Huyện An Phú",
    code: "886",
    parent_code: "89",
  },
  {
    label: "Thị xã Tân Châu",
    path_with_type: "Thị xã Tân Châu, Tỉnh An Giang",
    code: "887",
    parent_code: "89",
  },
  {
    label: "Huyện Phú Tân",
    code: "888",
    parent_code: "89",
  },
  {
    label: "Huyện Châu Phú",
    code: "889",
    parent_code: "89",
  },
  {
    label: "Huyện Tịnh Biên",
    code: "890",
    parent_code: "89",
  },
  {
    label: "Huyện Tri Tôn",
    code: "891",
    parent_code: "89",
  },
  {
    label: "Huyện Châu Thành",
    code: "892",
    parent_code: "89",
  },
  {
    label: "Huyện Chợ Mới",
    code: "893",
    parent_code: "89",
  },
  {
    label: "Huyện Thoại Sơn",
    code: "894",
    parent_code: "89",
  },
  {
    label: "Thành phố Kon Tum",
    path_with_type: "Thành phố Kon Tum, Tỉnh Kon Tum",
    code: "608",
    parent_code: "62",
  },
  {
    label: "Huyện Đắk Glei",
    code: "610",
    parent_code: "62",
  },
  {
    label: "Huyện Ngọc Hồi",
    code: "611",
    parent_code: "62",
  },
  {
    label: "Huyện Đắk Tô",
    code: "612",
    parent_code: "62",
  },
  {
    label: "Huyện Kon Plông",
    code: "613",
    parent_code: "62",
  },
  {
    label: "Huyện Kon Rẫy",
    code: "614",
    parent_code: "62",
  },
  {
    label: "Huyện Đắk Hà",
    code: "615",
    parent_code: "62",
  },
  {
    label: "Huyện Sa Thầy",
    code: "616",
    parent_code: "62",
  },
  {
    label: "Huyện Tu Mơ Rông",
    code: "617",
    parent_code: "62",
  },
  {
    label: "Huyện Ia H Drai",
    code: "618",
    parent_code: "62",
  },
  {
    label: "Thị xã Gia Nghĩa",
    path_with_type: "Thị xã Gia Nghĩa, Tỉnh Đắk Nông",
    code: "660",
    parent_code: "67",
  },
  {
    label: "Huyện Đăk Glong",
    code: "661",
    parent_code: "67",
  },
  {
    label: "Huyện Cư Jút",
    code: "662",
    parent_code: "67",
  },
  {
    label: "Huyện Đắk Mil",
    code: "663",
    parent_code: "67",
  },
  {
    label: "Huyện Krông Nô",
    code: "664",
    parent_code: "67",
  },
  {
    label: "Huyện Đắk Song",
    code: "665",
    parent_code: "67",
  },
  {
    label: "Huyện Đắk RLấp",
    code: "666",
    parent_code: "67",
  },
  {
    label: "Huyện Tuy Đức",
    code: "667",
    parent_code: "67",
  },
  {
    label: "Thành phố Sóc Trăng",
    path_with_type: "Thành phố Sóc Trăng, Tỉnh Sóc Trăng",
    code: "941",
    parent_code: "94",
  },
  {
    label: "Huyện Châu Thành",
    code: "942",
    parent_code: "94",
  },
  {
    label: "Huyện Kế Sách",
    code: "943",
    parent_code: "94",
  },
  {
    label: "Huyện Mỹ Tú",
    code: "944",
    parent_code: "94",
  },
  {
    label: "Huyện Cù Lao Dung",
    code: "945",
    parent_code: "94",
  },
  {
    label: "Huyện Long Phú",
    code: "946",
    parent_code: "94",
  },
  {
    label: "Huyện Mỹ Xuyên",
    code: "947",
    parent_code: "94",
  },
  {
    label: "Thị xã Ngã Năm",
    path_with_type: "Thị xã Ngã Năm, Tỉnh Sóc Trăng",
    code: "948",
    parent_code: "94",
  },
  {
    label: "Huyện Thạnh Trị",
    code: "949",
    parent_code: "94",
  },
  {
    label: "Thị xã Vĩnh Châu",
    path_with_type: "Thị xã Vĩnh Châu, Tỉnh Sóc Trăng",
    code: "950",
    parent_code: "94",
  },
  {
    label: "Huyện Trần Đề",
    code: "951",
    parent_code: "94",
  },
  {
    label: "Thị xã Phước Long",
    path_with_type: "Thị xã Phước Long, Tỉnh Bình Phước",
    code: "688",
    parent_code: "70",
  },
  {
    label: "Thị xã Đồng Xoài",
    path_with_type: "Thị xã Đồng Xoài, Tỉnh Bình Phước",
    code: "689",
    parent_code: "70",
  },
  {
    label: "Thị xã Bình Long",
    path_with_type: "Thị xã Bình Long, Tỉnh Bình Phước",
    code: "690",
    parent_code: "70",
  },
  {
    label: "Huyện Bù Gia Mập",
    code: "691",
    parent_code: "70",
  },
  {
    label: "Huyện Lộc Ninh",
    code: "692",
    parent_code: "70",
  },
  {
    label: "Huyện Bù Đốp",
    code: "693",
    parent_code: "70",
  },
  {
    label: "Huyện Hớn Quản",
    code: "694",
    parent_code: "70",
  },
  {
    label: "Huyện Đồng Phú",
    code: "695",
    parent_code: "70",
  },
  {
    label: "Huyện Bù Đăng",
    code: "696",
    parent_code: "70",
  },
  {
    label: "Huyện Chơn Thành",
    code: "697",
    parent_code: "70",
  },
  {
    label: "Huyện Phú Riềng",
    code: "698",
    parent_code: "70",
  },
  {
    label: "Thành phố Hưng Yên",
    path_with_type: "Thành phố Hưng Yên, Tỉnh Hưng Yên",
    code: "323",
    parent_code: "33",
  },
  {
    label: "Huyện Văn Lâm",
    code: "325",
    parent_code: "33",
  },
  {
    label: "Huyện Văn Giang",
    code: "326",
    parent_code: "33",
  },
  {
    label: "Huyện Yên Mỹ",
    code: "327",
    parent_code: "33",
  },
  {
    label: "Huyện Mỹ Hào",
    code: "328",
    parent_code: "33",
  },
  {
    label: "Huyện Ân Thi",
    code: "329",
    parent_code: "33",
  },
  {
    label: "Huyện Khoái Châu",
    code: "330",
    parent_code: "33",
  },
  {
    label: "Huyện Kim Động",
    code: "331",
    parent_code: "33",
  },
  {
    label: "Huyện Tiên Lữ",
    code: "332",
    parent_code: "33",
  },
  {
    label: "Huyện Phù Cừ",
    code: "333",
    parent_code: "33",
  },
  {
    label: "Thành phố Thanh Hóa",
    path_with_type: "Thành phố Thanh Hóa, Tỉnh Thanh Hóa",
    code: "380",
    parent_code: "38",
  },
  {
    label: "Thị xã Bỉm Sơn",
    path_with_type: "Thị xã Bỉm Sơn, Tỉnh Thanh Hóa",
    code: "381",
    parent_code: "38",
  },
  {
    label: "Thành phố Sầm Sơn",
    path_with_type: "Thành phố Sầm Sơn, Tỉnh Thanh Hóa",
    code: "382",
    parent_code: "38",
  },
  {
    label: "Huyện Mường Lát",
    code: "384",
    parent_code: "38",
  },
  {
    label: "Huyện Quan Hóa",
    code: "385",
    parent_code: "38",
  },
  {
    label: "Huyện Bá Thước",
    code: "386",
    parent_code: "38",
  },
  {
    label: "Huyện Quan Sơn",
    code: "387",
    parent_code: "38",
  },
  {
    label: "Huyện Lang Chánh",
    code: "388",
    parent_code: "38",
  },
  {
    label: "Huyện Ngọc Lặc",
    code: "389",
    parent_code: "38",
  },
  {
    label: "Huyện Cẩm Thủy",
    code: "390",
    parent_code: "38",
  },
  {
    label: "Huyện Thạch Thành",
    code: "391",
    parent_code: "38",
  },
  {
    label: "Huyện Hà Trung",
    code: "392",
    parent_code: "38",
  },
  {
    label: "Huyện Vĩnh Lộc",
    code: "393",
    parent_code: "38",
  },
  {
    label: "Huyện Yên Định",
    code: "394",
    parent_code: "38",
  },
  {
    label: "Huyện Thọ Xuân",
    code: "395",
    parent_code: "38",
  },
  {
    label: "Huyện Thường Xuân",
    code: "396",
    parent_code: "38",
  },
  {
    label: "Huyện Triệu Sơn",
    code: "397",
    parent_code: "38",
  },
  {
    label: "Huyện Thiệu Hóa",
    code: "398",
    parent_code: "38",
  },
  {
    label: "Huyện Hoằng Hóa",
    code: "399",
    parent_code: "38",
  },
  {
    label: "Huyện Hậu Lộc",
    code: "400",
    parent_code: "38",
  },
  {
    label: "Huyện Nga Sơn",
    code: "401",
    parent_code: "38",
  },
  {
    label: "Huyện Như Xuân",
    code: "402",
    parent_code: "38",
  },
  {
    label: "Huyện Như Thanh",
    code: "403",
    parent_code: "38",
  },
  {
    label: "Huyện Nông Cống",
    code: "404",
    parent_code: "38",
  },
  {
    label: "Huyện Đông Sơn",
    code: "405",
    parent_code: "38",
  },
  {
    label: "Huyện Quảng Xương",
    code: "406",
    parent_code: "38",
  },
  {
    label: "Huyện Tĩnh Gia",
    code: "407",
    parent_code: "38",
  },
  {
    label: "Thành phố Đông Hà",
    path_with_type: "Thành phố Đông Hà, Tỉnh Quảng Trị",
    code: "461",
    parent_code: "45",
  },
  {
    label: "Thị xã Quảng Trị",
    path_with_type: "Thị xã Quảng Trị, Tỉnh Quảng Trị",
    code: "462",
    parent_code: "45",
  },
  {
    label: "Huyện Vĩnh Linh",
    code: "464",
    parent_code: "45",
  },
  {
    label: "Huyện Hướng Hóa",
    code: "465",
    parent_code: "45",
  },
  {
    label: "Huyện Gio Linh",
    code: "466",
    parent_code: "45",
  },
  {
    label: "Huyện Đa Krông",
    code: "467",
    parent_code: "45",
  },
  {
    label: "Huyện Cam Lộ",
    code: "468",
    parent_code: "45",
  },
  {
    label: "Huyện Triệu Phong",
    code: "469",
    parent_code: "45",
  },
  {
    label: "Huyện Hải Lăng",
    code: "470",
    parent_code: "45",
  },
  {
    label: "Thành phố Tuyên Quang",
    path_with_type: "Thành phố Tuyên Quang, Tỉnh Tuyên Quang",
    code: "070",
    parent_code: "08",
  },
  {
    label: "Huyện Lâm Bình",
    code: "071",
    parent_code: "08",
  },
  {
    label: "Huyện Nà Hang",
    code: "072",
    parent_code: "08",
  },
  {
    label: "Huyện Chiêm Hóa",
    code: "073",
    parent_code: "08",
  },
  {
    label: "Huyện Hàm Yên",
    code: "074",
    parent_code: "08",
  },
  {
    label: "Huyện Yên Sơn",
    code: "075",
    parent_code: "08",
  },
  {
    label: "Huyện Sơn Dương",
    code: "076",
    parent_code: "08",
  },
  {
    label: "Thành phố Quảng Ngãi",
    path_with_type: "Thành phố Quảng Ngãi, Tỉnh Quảng Ngãi",
    code: "522",
    parent_code: "51",
  },
  {
    label: "Huyện Bình Sơn",
    code: "524",
    parent_code: "51",
  },
  {
    label: "Huyện Trà Bồng",
    code: "525",
    parent_code: "51",
  },
  {
    label: "Huyện Tây Trà",
    code: "526",
    parent_code: "51",
  },
  {
    label: "Huyện Sơn Tịnh",
    code: "527",
    parent_code: "51",
  },
  {
    label: "Huyện Tư Nghĩa",
    code: "528",
    parent_code: "51",
  },
  {
    label: "Huyện Sơn Hà",
    code: "529",
    parent_code: "51",
  },
  {
    label: "Huyện Sơn Tây",
    code: "530",
    parent_code: "51",
  },
  {
    label: "Huyện Minh Long",
    code: "531",
    parent_code: "51",
  },
  {
    label: "Huyện Nghĩa Hành",
    code: "532",
    parent_code: "51",
  },
  {
    label: "Huyện Mộ Đức",
    code: "533",
    parent_code: "51",
  },
  {
    label: "Huyện Đức Phổ",
    code: "534",
    parent_code: "51",
  },
  {
    label: "Huyện Ba Tơ",
    code: "535",
    parent_code: "51",
  },
  {
    label: "Huyện Lý Sơn",
    code: "536",
    parent_code: "51",
  },
  {
    label: "Quận Ba Đình",
    path_with_type: "Quận Ba Đình, Thành phố Hà Nội",
    code: "001",
    parent_code: "01",
  },
  {
    label: "Quận Hoàn Kiếm",
    path_with_type: "Quận Hoàn Kiếm, Thành phố Hà Nội",
    code: "002",
    parent_code: "01",
  },
  {
    label: "Quận Tây Hồ",
    path_with_type: "Quận Tây Hồ, Thành phố Hà Nội",
    code: "003",
    parent_code: "01",
  },
  {
    label: "Quận Long Biên",
    path_with_type: "Quận Long Biên, Thành phố Hà Nội",
    code: "004",
    parent_code: "01",
  },
  {
    label: "Quận Cầu Giấy",
    path_with_type: "Quận Cầu Giấy, Thành phố Hà Nội",
    code: "005",
    parent_code: "01",
  },
  {
    label: "Quận Đống Đa",
    path_with_type: "Quận Đống Đa, Thành phố Hà Nội",
    code: "006",
    parent_code: "01",
  },
  {
    label: "Quận Hai Bà Trưng",
    path_with_type: "Quận Hai Bà Trưng, Thành phố Hà Nội",
    code: "007",
    parent_code: "01",
  },
  {
    label: "Quận Hoàng Mai",
    path_with_type: "Quận Hoàng Mai, Thành phố Hà Nội",
    code: "008",
    parent_code: "01",
  },
  {
    label: "Quận Thanh Xuân",
    path_with_type: "Quận Thanh Xuân, Thành phố Hà Nội",
    code: "009",
    parent_code: "01",
  },
  {
    label: "Huyện Sóc Sơn",
    code: "016",
    parent_code: "01",
  },
  {
    label: "Huyện Đông Anh",
    code: "017",
    parent_code: "01",
  },
  {
    label: "Huyện Gia Lâm",
    code: "018",
    parent_code: "01",
  },
  {
    label: "Quận Nam Từ Liêm",
    path_with_type: "Quận Nam Từ Liêm, Thành phố Hà Nội",
    code: "019",
    parent_code: "01",
  },
  {
    label: "Huyện Thanh Trì",
    code: "020",
    parent_code: "01",
  },
  {
    label: "Quận Bắc Từ Liêm",
    path_with_type: "Quận Bắc Từ Liêm, Thành phố Hà Nội",
    code: "021",
    parent_code: "01",
  },
  {
    label: "Huyện Mê Linh",
    code: "250",
    parent_code: "01",
  },
  {
    label: "Quận Hà Đông",
    path_with_type: "Quận Hà Đông, Thành phố Hà Nội",
    code: "268",
    parent_code: "01",
  },
  {
    label: "Thị xã Sơn Tây",
    path_with_type: "Thị xã Sơn Tây, Thành phố Hà Nội",
    code: "269",
    parent_code: "01",
  },
  {
    label: "Huyện Ba Vì",
    code: "271",
    parent_code: "01",
  },
  {
    label: "Huyện Phúc Thọ",
    code: "272",
    parent_code: "01",
  },
  {
    label: "Huyện Đan Phượng",
    code: "273",
    parent_code: "01",
  },
  {
    label: "Huyện Hoài Đức",
    code: "274",
    parent_code: "01",
  },
  {
    label: "Huyện Quốc Oai",
    code: "275",
    parent_code: "01",
  },
  {
    label: "Huyện Thạch Thất",
    code: "276",
    parent_code: "01",
  },
  {
    label: "Huyện Chương Mỹ",
    code: "277",
    parent_code: "01",
  },
  {
    label: "Huyện Thanh Oai",
    code: "278",
    parent_code: "01",
  },
  {
    label: "Huyện Thường Tín",
    code: "279",
    parent_code: "01",
  },
  {
    label: "Huyện Phú Xuyên",
    code: "280",
    parent_code: "01",
  },
  {
    label: "Huyện Ứng Hòa",
    code: "281",
    parent_code: "01",
  },
  {
    label: "Huyện Mỹ Đức",
    code: "282",
    parent_code: "01",
  },
  {
    label: "Thành phố Lào Cai",
    path_with_type: "Thành phố Lào Cai, Tỉnh Lào Cai",
    code: "080",
    parent_code: "10",
  },
  {
    label: "Huyện Bát Xát",
    code: "082",
    parent_code: "10",
  },
  {
    label: "Huyện Mường Khương",
    code: "083",
    parent_code: "10",
  },
  {
    label: "Huyện Si Ma Cai",
    code: "084",
    parent_code: "10",
  },
  {
    label: "Huyện Bắc Hà",
    code: "085",
    parent_code: "10",
  },
  {
    label: "Huyện Bảo Thắng",
    code: "086",
    parent_code: "10",
  },
  {
    label: "Huyện Bảo Yên",
    code: "087",
    parent_code: "10",
  },
  {
    label: "Huyện Sa Pa",
    code: "088",
    parent_code: "10",
  },
  {
    label: "Huyện Văn Bàn",
    code: "089",
    parent_code: "10",
  },
  {
    label: "Thành phố Vĩnh Long",
    path_with_type: "Thành phố Vĩnh Long, Tỉnh Vĩnh Long",
    code: "855",
    parent_code: "86",
  },
  {
    label: "Huyện Long Hồ",
    code: "857",
    parent_code: "86",
  },
  {
    label: "Huyện Mang Thít",
    code: "858",
    parent_code: "86",
  },
  {
    label: "Huyện  Vũng Liêm",
    code: "859",
    parent_code: "86",
  },
  {
    label: "Huyện Tam Bình",
    code: "860",
    parent_code: "86",
  },
  {
    label: "Thị xã Bình Minh",
    path_with_type: "Thị xã Bình Minh, Tỉnh Vĩnh Long",
    code: "861",
    parent_code: "86",
  },
  {
    label: "Huyện Trà Ôn",
    code: "862",
    parent_code: "86",
  },
  {
    label: "Huyện Bình Tân",
    code: "863",
    parent_code: "86",
  },
  {
    label: "Thành phố Đà Lạt",
    path_with_type: "Thành phố Đà Lạt, Tỉnh Lâm Đồng",
    code: "672",
    parent_code: "68",
  },
  {
    label: "Thành phố Bảo Lộc",
    path_with_type: "Thành phố Bảo Lộc, Tỉnh Lâm Đồng",
    code: "673",
    parent_code: "68",
  },
  {
    label: "Huyện Đam Rông",
    code: "674",
    parent_code: "68",
  },
  {
    label: "Huyện Lạc Dương",
    code: "675",
    parent_code: "68",
  },
  {
    label: "Huyện Lâm Hà",
    code: "676",
    parent_code: "68",
  },
  {
    label: "Huyện Đơn Dương",
    code: "677",
    parent_code: "68",
  },
  {
    label: "Huyện Đức Trọng",
    code: "678",
    parent_code: "68",
  },
  {
    label: "Huyện Di Linh",
    code: "679",
    parent_code: "68",
  },
  {
    label: "Huyện Bảo Lâm",
    code: "680",
    parent_code: "68",
  },
  {
    label: "Huyện Đạ Huoai",
    code: "681",
    parent_code: "68",
  },
  {
    label: "Huyện Đạ Tẻh",
    code: "682",
    parent_code: "68",
  },
  {
    label: "Huyện Cát Tiên",
    code: "683",
    parent_code: "68",
  },
  {
    label: "Thành phố Qui Nhơn",
    path_with_type: "Thành phố Qui Nhơn, Tỉnh Bình Định",
    code: "540",
    parent_code: "52",
  },
  {
    label: "Huyện An Lão",
    code: "542",
    parent_code: "52",
  },
  {
    label: "Huyện Hoài Nhơn",
    code: "543",
    parent_code: "52",
  },
  {
    label: "Huyện Hoài Ân",
    code: "544",
    parent_code: "52",
  },
  {
    label: "Huyện Phù Mỹ",
    code: "545",
    parent_code: "52",
  },
  {
    label: "Huyện Vĩnh Thạnh",
    code: "546",
    parent_code: "52",
  },
  {
    label: "Huyện Tây Sơn",
    code: "547",
    parent_code: "52",
  },
  {
    label: "Huyện Phù Cát",
    code: "548",
    parent_code: "52",
  },
  {
    label: "Thị xã An Nhơn",
    path_with_type: "Thị xã An Nhơn, Tỉnh Bình Định",
    code: "549",
    parent_code: "52",
  },
  {
    label: "Huyện Tuy Phước",
    code: "550",
    parent_code: "52",
  },
  {
    label: "Huyện Vân Canh",
    code: "551",
    parent_code: "52",
  },
  {
    label: "Thành phố Vinh",
    path_with_type: "Thành phố Vinh, Tỉnh Nghệ An",
    code: "412",
    parent_code: "40",
  },
  {
    label: "Thị xã Cửa Lò",
    path_with_type: "Thị xã Cửa Lò, Tỉnh Nghệ An",
    code: "413",
    parent_code: "40",
  },
  {
    label: "Thị xã Thái Hoà",
    path_with_type: "Thị xã Thái Hoà, Tỉnh Nghệ An",
    code: "414",
    parent_code: "40",
  },
  {
    label: "Huyện Quế Phong",
    code: "415",
    parent_code: "40",
  },
  {
    label: "Huyện Quỳ Châu",
    code: "416",
    parent_code: "40",
  },
  {
    label: "Huyện Kỳ Sơn",
    code: "417",
    parent_code: "40",
  },
  {
    label: "Huyện Tương Dương",
    code: "418",
    parent_code: "40",
  },
  {
    label: "Huyện Nghĩa Đàn",
    code: "419",
    parent_code: "40",
  },
  {
    label: "Huyện Quỳ Hợp",
    code: "420",
    parent_code: "40",
  },
  {
    label: "Huyện Quỳnh Lưu",
    code: "421",
    parent_code: "40",
  },
  {
    label: "Huyện Con Cuông",
    code: "422",
    parent_code: "40",
  },
  {
    label: "Huyện Tân Kỳ",
    code: "423",
    parent_code: "40",
  },
  {
    label: "Huyện Anh Sơn",
    code: "424",
    parent_code: "40",
  },
  {
    label: "Huyện Diễn Châu",
    code: "425",
    parent_code: "40",
  },
  {
    label: "Huyện Yên Thành",
    code: "426",
    parent_code: "40",
  },
  {
    label: "Huyện Đô Lương",
    code: "427",
    parent_code: "40",
  },
  {
    label: "Huyện Thanh Chương",
    code: "428",
    parent_code: "40",
  },
  {
    label: "Huyện Nghi Lộc",
    code: "429",
    parent_code: "40",
  },
  {
    label: "Huyện Nam Đàn",
    code: "430",
    parent_code: "40",
  },
  {
    label: "Huyện Hưng Nguyên",
    code: "431",
    parent_code: "40",
  },
  {
    label: "Thị xã Hoàng Mai",
    path_with_type: "Thị xã Hoàng Mai, Tỉnh Nghệ An",
    code: "432",
    parent_code: "40",
  },
  {
    label: "Thành phố Rạch Giá",
    path_with_type: "Thành phố Rạch Giá, Tỉnh Kiên Giang",
    code: "899",
    parent_code: "91",
  },
  {
    label: "Thị xã Hà Tiên",
    path_with_type: "Thị xã Hà Tiên, Tỉnh Kiên Giang",
    code: "900",
    parent_code: "91",
  },
  {
    label: "Huyện Kiên Lương",
    code: "902",
    parent_code: "91",
  },
  {
    label: "Huyện Hòn Đất",
    code: "903",
    parent_code: "91",
  },
  {
    label: "Huyện Tân Hiệp",
    code: "904",
    parent_code: "91",
  },
  {
    label: "Huyện Châu Thành",
    code: "905",
    parent_code: "91",
  },
  {
    label: "Huyện Giồng Riềng",
    code: "906",
    parent_code: "91",
  },
  {
    label: "Huyện Gò Quao",
    code: "907",
    parent_code: "91",
  },
  {
    label: "Huyện An Biên",
    code: "908",
    parent_code: "91",
  },
  {
    label: "Huyện An Minh",
    code: "909",
    parent_code: "91",
  },
  {
    label: "Huyện Vĩnh Thuận",
    code: "910",
    parent_code: "91",
  },
  {
    label: "Huyện Phú Quốc",
    code: "911",
    parent_code: "91",
  },
  {
    label: "Huyện Kiên Hải",
    code: "912",
    parent_code: "91",
  },
  {
    label: "Huyện U Minh Thượng",
    code: "913",
    parent_code: "91",
  },
  {
    label: "Huyện Giang Thành",
    code: "914",
    parent_code: "91",
  },
  {
    label: "Thành phố Hà Giang",
    path_with_type: "Thành phố Hà Giang, Tỉnh Hà Giang",
    code: "024",
    parent_code: "02",
  },
  {
    label: "Huyện Đồng Văn",
    code: "026",
    parent_code: "02",
  },
  {
    label: "Huyện Mèo Vạc",
    code: "027",
    parent_code: "02",
  },
  {
    label: "Huyện Yên Minh",
    code: "028",
    parent_code: "02",
  },
  {
    label: "Huyện Quản Bạ",
    code: "029",
    parent_code: "02",
  },
  {
    label: "Huyện Vị Xuyên",
    code: "030",
    parent_code: "02",
  },
  {
    label: "Huyện Bắc Mê",
    code: "031",
    parent_code: "02",
  },
  {
    label: "Huyện Hoàng Su Phì",
    code: "032",
    parent_code: "02",
  },
  {
    label: "Huyện Xín Mần",
    code: "033",
    parent_code: "02",
  },
  {
    label: "Huyện Bắc Quang",
    code: "034",
    parent_code: "02",
  },
  {
    label: "Huyện Quang Bình",
    code: "035",
    parent_code: "02",
  },
  {
    label: "Thành phố Tuy Hoà",
    path_with_type: "Thành phố Tuy Hoà, Tỉnh Phú Yên",
    code: "555",
    parent_code: "54",
  },
  {
    label: "Thị xã Sông Cầu",
    path_with_type: "Thị xã Sông Cầu, Tỉnh Phú Yên",
    code: "557",
    parent_code: "54",
  },
  {
    label: "Huyện Đồng Xuân",
    code: "558",
    parent_code: "54",
  },
  {
    label: "Huyện Tuy An",
    code: "559",
    parent_code: "54",
  },
  {
    label: "Huyện Sơn Hòa",
    code: "560",
    parent_code: "54",
  },
  {
    label: "Huyện Sông Hinh",
    code: "561",
    parent_code: "54",
  },
  {
    label: "Huyện Tây Hoà",
    code: "562",
    parent_code: "54",
  },
  {
    label: "Huyện Phú Hoà",
    code: "563",
    parent_code: "54",
  },
  {
    label: "Huyện Đông Hòa",
    code: "564",
    parent_code: "54",
  },
  {
    label: "Thành phố Lạng Sơn",
    path_with_type: "Thành phố Lạng Sơn, Tỉnh Lạng Sơn",
    code: "178",
    parent_code: "20",
  },
  {
    label: "Huyện Tràng Định",
    code: "180",
    parent_code: "20",
  },
  {
    label: "Huyện Bình Gia",
    code: "181",
    parent_code: "20",
  },
  {
    label: "Huyện Văn Lãng",
    code: "182",
    parent_code: "20",
  },
  {
    label: "Huyện Cao Lộc",
    code: "183",
    parent_code: "20",
  },
  {
    label: "Huyện Văn Quan",
    code: "184",
    parent_code: "20",
  },
  {
    label: "Huyện Bắc Sơn",
    code: "185",
    parent_code: "20",
  },
  {
    label: "Huyện Hữu Lũng",
    code: "186",
    parent_code: "20",
  },
  {
    label: "Huyện Chi Lăng",
    code: "187",
    parent_code: "20",
  },
  {
    label: "Huyện Lộc Bình",
    code: "188",
    parent_code: "20",
  },
  {
    label: "Huyện Đình Lập",
    code: "189",
    parent_code: "20",
  },
  {
    label: "Quận Liên Chiểu",
    path_with_type: "Quận Liên Chiểu, Thành phố Đà Nẵng",
    code: "490",
    parent_code: "48",
  },
  {
    label: "Quận Thanh Khê",
    path_with_type: "Quận Thanh Khê, Thành phố Đà Nẵng",
    code: "491",
    parent_code: "48",
  },
  {
    label: "Quận Hải Châu",
    path_with_type: "Quận Hải Châu, Thành phố Đà Nẵng",
    code: "492",
    parent_code: "48",
  },
  {
    label: "Quận Sơn Trà",
    path_with_type: "Quận Sơn Trà, Thành phố Đà Nẵng",
    code: "493",
    parent_code: "48",
  },
  {
    label: "Quận Ngũ Hành Sơn",
    path_with_type: "Quận Ngũ Hành Sơn, Thành phố Đà Nẵng",
    code: "494",
    parent_code: "48",
  },
  {
    label: "Quận Cẩm Lệ",
    path_with_type: "Quận Cẩm Lệ, Thành phố Đà Nẵng",
    code: "495",
    parent_code: "48",
  },
  {
    label: "Huyện Hòa Vang",
    code: "497",
    parent_code: "48",
  },
  {
    label: "Thành phố Sơn La",
    path_with_type: "Thành phố Sơn La, Tỉnh Sơn La",
    code: "116",
    parent_code: "14",
  },
  {
    label: "Huyện Quỳnh Nhai",
    code: "118",
    parent_code: "14",
  },
  {
    label: "Huyện Thuận Châu",
    code: "119",
    parent_code: "14",
  },
  {
    label: "Huyện Mường La",
    code: "120",
    parent_code: "14",
  },
  {
    label: "Huyện Bắc Yên",
    code: "121",
    parent_code: "14",
  },
  {
    label: "Huyện Phù Yên",
    code: "122",
    parent_code: "14",
  },
  {
    label: "Huyện Mộc Châu",
    code: "123",
    parent_code: "14",
  },
  {
    label: "Huyện Yên Châu",
    code: "124",
    parent_code: "14",
  },
  {
    label: "Huyện Mai Sơn",
    code: "125",
    parent_code: "14",
  },
  {
    label: "Huyện Sông Mã",
    code: "126",
    parent_code: "14",
  },
  {
    label: "Huyện Sốp Cộp",
    code: "127",
    parent_code: "14",
  },
  {
    label: "Huyện Vân Hồ",
    code: "128",
    parent_code: "14",
  },
  {
    label: "Thành phố Tây Ninh",
    path_with_type: "Thành phố Tây Ninh, Tỉnh Tây Ninh",
    code: "703",
    parent_code: "72",
  },
  {
    label: "Huyện Tân Biên",
    code: "705",
    parent_code: "72",
  },
  {
    label: "Huyện Tân Châu",
    code: "706",
    parent_code: "72",
  },
  {
    label: "Huyện Dương Minh Châu",
    code: "707",
    parent_code: "72",
  },
  {
    label: "Huyện Châu Thành",
    code: "708",
    parent_code: "72",
  },
  {
    label: "Huyện Hòa Thành",
    code: "709",
    parent_code: "72",
  },
  {
    label: "Huyện Gò Dầu",
    code: "710",
    parent_code: "72",
  },
  {
    label: "Huyện Bến Cầu",
    code: "711",
    parent_code: "72",
  },
  {
    label: "Huyện Trảng Bàng",
    code: "712",
    parent_code: "72",
  },
  {
    label: "Thành phố Nam Định",
    path_with_type: "Thành phố Nam Định, Tỉnh Nam Định",
    code: "356",
    parent_code: "36",
  },
  {
    label: "Huyện Mỹ Lộc",
    code: "358",
    parent_code: "36",
  },
  {
    label: "Huyện Vụ Bản",
    code: "359",
    parent_code: "36",
  },
  {
    label: "Huyện Ý Yên",
    code: "360",
    parent_code: "36",
  },
  {
    label: "Huyện Nghĩa Hưng",
    code: "361",
    parent_code: "36",
  },
  {
    label: "Huyện Nam Trực",
    code: "362",
    parent_code: "36",
  },
  {
    label: "Huyện Trực Ninh",
    code: "363",
    parent_code: "36",
  },
  {
    label: "Huyện Xuân Trường",
    code: "364",
    parent_code: "36",
  },
  {
    label: "Huyện Giao Thủy",
    code: "365",
    parent_code: "36",
  },
  {
    label: "Huyện Hải Hậu",
    code: "366",
    parent_code: "36",
  },
  {
    label: "Thành phố Lai Châu",
    path_with_type: "Thành phố Lai Châu, Tỉnh Lai Châu",
    code: "105",
    parent_code: "12",
  },
  {
    label: "Huyện Tam Đường",
    code: "106",
    parent_code: "12",
  },
  {
    label: "Huyện Mường Tè",
    code: "107",
    parent_code: "12",
  },
  {
    label: "Huyện Sìn Hồ",
    code: "108",
    parent_code: "12",
  },
  {
    label: "Huyện Phong Thổ",
    code: "109",
    parent_code: "12",
  },
  {
    label: "Huyện Than Uyên",
    code: "110",
    parent_code: "12",
  },
  {
    label: "Huyện Tân Uyên",
    code: "111",
    parent_code: "12",
  },
  {
    label: "Huyện Nậm Nhùn",
    code: "112",
    parent_code: "12",
  },
  {
    label: "Thành phố Bến Tre",
    path_with_type: "Thành phố Bến Tre, Tỉnh Bến Tre",
    code: "829",
    parent_code: "83",
  },
  {
    label: "Huyện Châu Thành",
    code: "831",
    parent_code: "83",
  },
  {
    label: "Huyện Chợ Lách",
    code: "832",
    parent_code: "83",
  },
  {
    label: "Huyện Mỏ Cày Nam",
    code: "833",
    parent_code: "83",
  },
  {
    label: "Huyện Giồng Trôm",
    code: "834",
    parent_code: "83",
  },
  {
    label: "Huyện Bình Đại",
    code: "835",
    parent_code: "83",
  },
  {
    label: "Huyện Ba Tri",
    code: "836",
    parent_code: "83",
  },
  {
    label: "Huyện Thạnh Phú",
    code: "837",
    parent_code: "83",
  },
  {
    label: "Huyện Mỏ Cày Bắc",
    code: "838",
    parent_code: "83",
  },
  {
    label: "Thành phố Nha Trang",
    path_with_type: "Thành phố Nha Trang, Tỉnh Khánh Hòa",
    code: "568",
    parent_code: "56",
  },
  {
    label: "Thành phố Cam Ranh",
    path_with_type: "Thành phố Cam Ranh, Tỉnh Khánh Hòa",
    code: "569",
    parent_code: "56",
  },
  {
    label: "Huyện Cam Lâm",
    code: "570",
    parent_code: "56",
  },
  {
    label: "Huyện Vạn Ninh",
    code: "571",
    parent_code: "56",
  },
  {
    label: "Thị xã Ninh Hòa",
    path_with_type: "Thị xã Ninh Hòa, Tỉnh Khánh Hòa",
    code: "572",
    parent_code: "56",
  },
  {
    label: "Huyện Khánh Vĩnh",
    code: "573",
    parent_code: "56",
  },
  {
    label: "Huyện Diên Khánh",
    code: "574",
    parent_code: "56",
  },
  {
    label: "Huyện Khánh Sơn",
    code: "575",
    parent_code: "56",
  },
  {
    label: "Huyện Trường Sa",
    code: "576",
    parent_code: "56",
  },
  {
    label: "Thành phố Phan Thiết",
    path_with_type: "Thành phố Phan Thiết, Tỉnh Bình Thuận",
    code: "593",
    parent_code: "60",
  },
  {
    label: "Thị xã La Gi",
    path_with_type: "Thị xã La Gi, Tỉnh Bình Thuận",
    code: "594",
    parent_code: "60",
  },
  {
    label: "Huyện Tuy Phong",
    code: "595",
    parent_code: "60",
  },
  {
    label: "Huyện Bắc Bình",
    code: "596",
    parent_code: "60",
  },
  {
    label: "Huyện Hàm Thuận Bắc",
    code: "597",
    parent_code: "60",
  },
  {
    label: "Huyện Hàm Thuận Nam",
    code: "598",
    parent_code: "60",
  },
  {
    label: "Huyện Tánh Linh",
    code: "599",
    parent_code: "60",
  },
  {
    label: "Huyện Đức Linh",
    code: "600",
    parent_code: "60",
  },
  {
    label: "Huyện Hàm Tân",
    code: "601",
    parent_code: "60",
  },
  {
    label: "Huyện Phú Quí",
    code: "602",
    parent_code: "60",
  },
  {
    label: "Thành phố Cao Bằng",
    path_with_type: "Thành phố Cao Bằng, Tỉnh Cao Bằng",
    code: "040",
    parent_code: "04",
  },
  {
    label: "Huyện Bảo Lâm",
    code: "042",
    parent_code: "04",
  },
  {
    label: "Huyện Bảo Lạc",
    code: "043",
    parent_code: "04",
  },
  {
    label: "Huyện Thông Nông",
    code: "044",
    parent_code: "04",
  },
  {
    label: "Huyện Hà Quảng",
    code: "045",
    parent_code: "04",
  },
  {
    label: "Huyện Trà Lĩnh",
    code: "046",
    parent_code: "04",
  },
  {
    label: "Huyện Trùng Khánh",
    code: "047",
    parent_code: "04",
  },
  {
    label: "Huyện Hạ Lang",
    code: "048",
    parent_code: "04",
  },
  {
    label: "Huyện Quảng Uyên",
    code: "049",
    parent_code: "04",
  },
  {
    label: "Huyện Phục Hoà",
    code: "050",
    parent_code: "04",
  },
  {
    label: "Huyện Hoà An",
    code: "051",
    parent_code: "04",
  },
  {
    label: "Huyện Nguyên Bình",
    code: "052",
    parent_code: "04",
  },
  {
    label: "Huyện Thạch An",
    code: "053",
    parent_code: "04",
  },
  {
    label: "Quận Hồng Bàng",
    path_with_type: "Quận Hồng Bàng, Thành phố Hải Phòng",
    code: "303",
    parent_code: "31",
  },
  {
    label: "Quận Ngô Quyền",
    path_with_type: "Quận Ngô Quyền, Thành phố Hải Phòng",
    code: "304",
    parent_code: "31",
  },
  {
    label: "Quận Lê Chân",
    path_with_type: "Quận Lê Chân, Thành phố Hải Phòng",
    code: "305",
    parent_code: "31",
  },
  {
    label: "Quận Hải An",
    path_with_type: "Quận Hải An, Thành phố Hải Phòng",
    code: "306",
    parent_code: "31",
  },
  {
    label: "Quận Kiến An",
    path_with_type: "Quận Kiến An, Thành phố Hải Phòng",
    code: "307",
    parent_code: "31",
  },
  {
    label: "Quận Đồ Sơn",
    path_with_type: "Quận Đồ Sơn, Thành phố Hải Phòng",
    code: "308",
    parent_code: "31",
  },
  {
    label: "Quận Dương Kinh",
    path_with_type: "Quận Dương Kinh, Thành phố Hải Phòng",
    code: "309",
    parent_code: "31",
  },
  {
    label: "Huyện Thuỷ Nguyên",
    code: "311",
    parent_code: "31",
  },
  {
    label: "Huyện An Dương",
    code: "312",
    parent_code: "31",
  },
  {
    label: "Huyện An Lão",
    code: "313",
    parent_code: "31",
  },
  {
    label: "Huyện Kiến Thuỵ",
    code: "314",
    parent_code: "31",
  },
  {
    label: "Huyện Tiên Lãng",
    code: "315",
    parent_code: "31",
  },
  {
    label: "Huyện Vĩnh Bảo",
    code: "316",
    parent_code: "31",
  },
  {
    label: "Huyện Cát Hải",
    code: "317",
    parent_code: "31",
  },
  {
    label: "Thành phố Ninh Bình",
    path_with_type: "Thành phố Ninh Bình, Tỉnh Ninh Bình",
    code: "369",
    parent_code: "37",
  },
  {
    label: "Thành phố Tam Điệp",
    path_with_type: "Thành phố Tam Điệp, Tỉnh Ninh Bình",
    code: "370",
    parent_code: "37",
  },
  {
    label: "Huyện Nho Quan",
    code: "372",
    parent_code: "37",
  },
  {
    label: "Huyện Gia Viễn",
    code: "373",
    parent_code: "37",
  },
  {
    label: "Huyện Hoa Lư",
    code: "374",
    parent_code: "37",
  },
  {
    label: "Huyện Yên Khánh",
    code: "375",
    parent_code: "37",
  },
  {
    label: "Huyện Kim Sơn",
    code: "376",
    parent_code: "37",
  },
  {
    label: "Huyện Yên Mô",
    code: "377",
    parent_code: "37",
  },
  {
    label: "Thành phố Yên Bái",
    path_with_type: "Thành phố Yên Bái, Tỉnh Yên Bái",
    code: "132",
    parent_code: "15",
  },
  {
    label: "Thị xã Nghĩa Lộ",
    path_with_type: "Thị xã Nghĩa Lộ, Tỉnh Yên Bái",
    code: "133",
    parent_code: "15",
  },
  {
    label: "Huyện Lục Yên",
    code: "135",
    parent_code: "15",
  },
  {
    label: "Huyện Văn Yên",
    code: "136",
    parent_code: "15",
  },
  {
    label: "Huyện Mù Căng Chải",
    code: "137",
    parent_code: "15",
  },
  {
    label: "Huyện Trấn Yên",
    code: "138",
    parent_code: "15",
  },
  {
    label: "Huyện Trạm Tấu",
    code: "139",
    parent_code: "15",
  },
  {
    label: "Huyện Văn Chấn",
    code: "140",
    parent_code: "15",
  },
  {
    label: "Huyện Yên Bình",
    code: "141",
    parent_code: "15",
  },
  {
    label: "Thành phố Pleiku",
    path_with_type: "Thành phố Pleiku, Tỉnh Gia Lai",
    code: "622",
    parent_code: "64",
  },
  {
    label: "Thị xã An Khê",
    path_with_type: "Thị xã An Khê, Tỉnh Gia Lai",
    code: "623",
    parent_code: "64",
  },
  {
    label: "Thị xã Ayun Pa",
    path_with_type: "Thị xã Ayun Pa, Tỉnh Gia Lai",
    code: "624",
    parent_code: "64",
  },
  {
    label: "Huyện KBang",
    code: "625",
    parent_code: "64",
  },
  {
    label: "Huyện Đăk Đoa",
    code: "626",
    parent_code: "64",
  },
  {
    label: "Huyện Chư Păh",
    code: "627",
    parent_code: "64",
  },
  {
    label: "Huyện Ia Grai",
    code: "628",
    parent_code: "64",
  },
  {
    label: "Huyện Mang Yang",
    code: "629",
    parent_code: "64",
  },
  {
    label: "Huyện Kông Chro",
    code: "630",
    parent_code: "64",
  },
  {
    label: "Huyện Đức Cơ",
    code: "631",
    parent_code: "64",
  },
  {
    label: "Huyện Chư Prông",
    code: "632",
    parent_code: "64",
  },
  {
    label: "Huyện Chư Sê",
    code: "633",
    parent_code: "64",
  },
  {
    label: "Huyện Đăk Pơ",
    code: "634",
    parent_code: "64",
  },
  {
    label: "Huyện Ia Pa",
    code: "635",
    parent_code: "64",
  },
  {
    label: "Huyện Krông Pa",
    code: "637",
    parent_code: "64",
  },
  {
    label: "Huyện Phú Thiện",
    code: "638",
    parent_code: "64",
  },
  {
    label: "Huyện Chư Pưh",
    code: "639",
    parent_code: "64",
  },
  {
    label: "Thành phố Hòa Bình",
    path_with_type: "Thành phố Hòa Bình, Tỉnh Hoà Bình",
    code: "148",
    parent_code: "17",
  },
  {
    label: "Huyện Đà Bắc",
    code: "150",
    parent_code: "17",
  },
  {
    label: "Huyện Kỳ Sơn",
    code: "151",
    parent_code: "17",
  },
  {
    label: "Huyện Lương Sơn",
    code: "152",
    parent_code: "17",
  },
  {
    label: "Huyện Kim Bôi",
    code: "153",
    parent_code: "17",
  },
  {
    label: "Huyện Cao Phong",
    code: "154",
    parent_code: "17",
  },
  {
    label: "Huyện Tân Lạc",
    code: "155",
    parent_code: "17",
  },
  {
    label: "Huyện Mai Châu",
    code: "156",
    parent_code: "17",
  },
  {
    label: "Huyện Lạc Sơn",
    code: "157",
    parent_code: "17",
  },
  {
    label: "Huyện Yên Thủy",
    code: "158",
    parent_code: "17",
  },
  {
    label: "Huyện Lạc Thủy",
    code: "159",
    parent_code: "17",
  },
  {
    label: "Thành phố Vũng Tàu",
    path_with_type: "Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu",
    code: "747",
    parent_code: "77",
  },
  {
    label: "Thành phố Bà Rịa",
    path_with_type: "Thành phố Bà Rịa, Tỉnh Bà Rịa - Vũng Tàu",
    code: "748",
    parent_code: "77",
  },
  {
    label: "Huyện Châu Đức",
    code: "750",
    parent_code: "77",
  },
  {
    label: "Huyện Xuyên Mộc",
    code: "751",
    parent_code: "77",
  },
  {
    label: "Huyện Long Điền",
    code: "752",
    parent_code: "77",
  },
  {
    label: "Huyện Đất Đỏ",
    code: "753",
    parent_code: "77",
  },
  {
    label: "Huyện Tân Thành",
    code: "754",
    parent_code: "77",
  },
  {
    label: "Thành phố Cà Mau",
    path_with_type: "Thành phố Cà Mau, Tỉnh Cà Mau",
    code: "964",
    parent_code: "96",
  },
  {
    label: "Huyện U Minh",
    code: "966",
    parent_code: "96",
  },
  {
    label: "Huyện Thới Bình",
    code: "967",
    parent_code: "96",
  },
  {
    label: "Huyện Trần Văn Thời",
    code: "968",
    parent_code: "96",
  },
  {
    label: "Huyện Cái Nước",
    code: "969",
    parent_code: "96",
  },
  {
    label: "Huyện Đầm Dơi",
    code: "970",
    parent_code: "96",
  },
  {
    label: "Huyện Năm Căn",
    code: "971",
    parent_code: "96",
  },
  {
    label: "Huyện Phú Tân",
    code: "972",
    parent_code: "96",
  },
  {
    label: "Huyện Ngọc Hiển",
    code: "973",
    parent_code: "96",
  },
  {
    label: "Thành phố Thủ Dầu Một",
    path_with_type: "Thành phố Thủ Dầu Một, Tỉnh Bình Dương",
    code: "718",
    parent_code: "74",
  },
  {
    label: "Huyện Bàu Bàng",
    code: "719",
    parent_code: "74",
  },
  {
    label: "Huyện Dầu Tiếng",
    code: "720",
    parent_code: "74",
  },
  {
    label: "Thị xã Bến Cát",
    path_with_type: "Thị xã Bến Cát, Tỉnh Bình Dương",
    code: "721",
    parent_code: "74",
  },
  {
    label: "Huyện Phú Giáo",
    code: "722",
    parent_code: "74",
  },
  {
    label: "Thị xã Tân Uyên",
    path_with_type: "Thị xã Tân Uyên, Tỉnh Bình Dương",
    code: "723",
    parent_code: "74",
  },
  {
    label: "Thị xã Dĩ An",
    path_with_type: "Thị xã Dĩ An, Tỉnh Bình Dương",
    code: "724",
    parent_code: "74",
  },
  {
    label: "Thị xã Thuận An",
    path_with_type: "Thị xã Thuận An, Tỉnh Bình Dương",
    code: "725",
    parent_code: "74",
  },
  {
    label: "Huyện Bắc Tân Uyên",
    code: "726",
    parent_code: "74",
  },
  {
    label: "Quận Ninh Kiều",
    path_with_type: "Quận Ninh Kiều, Thành phố Cần Thơ",
    code: "916",
    parent_code: "92",
  },
  {
    label: "Quận Ô Môn",
    path_with_type: "Quận Ô Môn, Thành phố Cần Thơ",
    code: "917",
    parent_code: "92",
  },
  {
    label: "Quận Bình Thuỷ",
    path_with_type: "Quận Bình Thuỷ, Thành phố Cần Thơ",
    code: "918",
    parent_code: "92",
  },
  {
    label: "Quận Cái Răng",
    path_with_type: "Quận Cái Răng, Thành phố Cần Thơ",
    code: "919",
    parent_code: "92",
  },
  {
    label: "Quận Thốt Nốt",
    path_with_type: "Quận Thốt Nốt, Thành phố Cần Thơ",
    code: "923",
    parent_code: "92",
  },
  {
    label: "Huyện Vĩnh Thạnh",
    code: "924",
    parent_code: "92",
  },
  {
    label: "Huyện Cờ Đỏ",
    code: "925",
    parent_code: "92",
  },
  {
    label: "Huyện Phong Điền",
    code: "926",
    parent_code: "92",
  },
  {
    label: "Huyện Thới Lai",
    code: "927",
    parent_code: "92",
  },
  {
    label: "Thành phố Huế",
    path_with_type: "Thành phố Huế, Tỉnh Thừa Thiên Huế",
    code: "474",
    parent_code: "46",
  },
  {
    label: "Huyện Phong Điền",
    code: "476",
    parent_code: "46",
  },
  {
    label: "Huyện Quảng Điền",
    code: "477",
    parent_code: "46",
  },
  {
    label: "Huyện Phú Vang",
    code: "478",
    parent_code: "46",
  },
  {
    label: "Thị xã Hương Thủy",
    path_with_type: "Thị xã Hương Thủy, Tỉnh Thừa Thiên Huế",
    code: "479",
    parent_code: "46",
  },
  {
    label: "Thị xã Hương Trà",
    path_with_type: "Thị xã Hương Trà, Tỉnh Thừa Thiên Huế",
    code: "480",
    parent_code: "46",
  },
  {
    label: "Huyện A Lưới",
    code: "481",
    parent_code: "46",
  },
  {
    label: "Huyện Phú Lộc",
    code: "482",
    parent_code: "46",
  },
  {
    label: "Huyện Nam Đông",
    code: "483",
    parent_code: "46",
  },
  {
    label: "Thành phố Biên Hòa",
    path_with_type: "Thành phố Biên Hòa, Tỉnh Đồng Nai",
    code: "731",
    parent_code: "75",
  },
  {
    label: "Thị xã Long Khánh",
    path_with_type: "Thị xã Long Khánh, Tỉnh Đồng Nai",
    code: "732",
    parent_code: "75",
  },
  {
    label: "Huyện Tân Phú",
    code: "734",
    parent_code: "75",
  },
  {
    label: "Huyện Vĩnh Cửu",
    code: "735",
    parent_code: "75",
  },
  {
    label: "Huyện Định Quán",
    code: "736",
    parent_code: "75",
  },
  {
    label: "Huyện Trảng Bom",
    code: "737",
    parent_code: "75",
  },
  {
    label: "Huyện Thống Nhất",
    code: "738",
    parent_code: "75",
  },
  {
    label: "Huyện Cẩm Mỹ",
    code: "739",
    parent_code: "75",
  },
  {
    label: "Huyện Long Thành",
    code: "740",
    parent_code: "75",
  },
  {
    label: "Huyện Xuân Lộc",
    code: "741",
    parent_code: "75",
  },
  {
    label: "Huyện Nhơn Trạch",
    code: "742",
    parent_code: "75",
  },
  {
    label: "Thành phố Mỹ Tho",
    path_with_type: "Thành phố Mỹ Tho, Tỉnh Tiền Giang",
    code: "815",
    parent_code: "82",
  },
  {
    label: "Thị xã Gò Công",
    path_with_type: "Thị xã Gò Công, Tỉnh Tiền Giang",
    code: "816",
    parent_code: "82",
  },
  {
    label: "Thị xã Cai Lậy",
    path_with_type: "Thị xã Cai Lậy, Tỉnh Tiền Giang",
    code: "817",
    parent_code: "82",
  },
  {
    label: "Huyện Tân Phước",
    code: "818",
    parent_code: "82",
  },
  {
    label: "Huyện Cái Bè",
    code: "819",
    parent_code: "82",
  },
  {
    label: "Huyện Cai Lậy",
    code: "820",
    parent_code: "82",
  },
  {
    label: "Huyện Châu Thành",
    code: "821",
    parent_code: "82",
  },
  {
    label: "Huyện Chợ Gạo",
    code: "822",
    parent_code: "82",
  },
  {
    label: "Huyện Gò Công Tây",
    code: "823",
    parent_code: "82",
  },
  {
    label: "Huyện Gò Công Đông",
    code: "824",
    parent_code: "82",
  },
  {
    label: "Huyện Tân Phú Đông",
    code: "825",
    parent_code: "82",
  },
  {
    label: "Thành phố Điện Biên Phủ",
    path_with_type: "Thành phố Điện Biên Phủ, Tỉnh Điện Biên",
    code: "094",
    parent_code: "11",
  },
  {
    label: "Thị xã Mường Lay",
    path_with_type: "Thị xã Mường Lay, Tỉnh Điện Biên",
    code: "095",
    parent_code: "11",
  },
  {
    label: "Huyện Mường Nhé",
    code: "096",
    parent_code: "11",
  },
  {
    label: "Huyện Mường Chà",
    code: "097",
    parent_code: "11",
  },
  {
    label: "Huyện Tủa Chùa",
    code: "098",
    parent_code: "11",
  },
  {
    label: "Huyện Tuần Giáo",
    code: "099",
    parent_code: "11",
  },
  {
    label: "Huyện Điện Biên",
    code: "100",
    parent_code: "11",
  },
  {
    label: "Huyện Điện Biên Đông",
    code: "101",
    parent_code: "11",
  },
  {
    label: "Huyện Mường Ảng",
    code: "102",
    parent_code: "11",
  },
  {
    label: "Huyện Nậm Pồ",
    code: "103",
    parent_code: "11",
  },
  {
    label: "Thành phố Vĩnh Yên",
    path_with_type: "Thành phố Vĩnh Yên, Tỉnh Vĩnh Phúc",
    code: "243",
    parent_code: "26",
  },
  {
    label: "Thị xã Phúc Yên",
    path_with_type: "Thị xã Phúc Yên, Tỉnh Vĩnh Phúc",
    code: "244",
    parent_code: "26",
  },
  {
    label: "Huyện Lập Thạch",
    code: "246",
    parent_code: "26",
  },
  {
    label: "Huyện Tam Dương",
    code: "247",
    parent_code: "26",
  },
  {
    label: "Huyện Tam Đảo",
    code: "248",
    parent_code: "26",
  },
  {
    label: "Huyện Bình Xuyên",
    code: "249",
    parent_code: "26",
  },
  {
    label: "Huyện Yên Lạc",
    code: "251",
    parent_code: "26",
  },
  {
    label: "Huyện Vĩnh Tường",
    code: "252",
    parent_code: "26",
  },
  {
    label: "Huyện Sông Lô",
    code: "253",
    parent_code: "26",
  },
  {
    label: "Thành phố Tam Kỳ",
    path_with_type: "Thành phố Tam Kỳ, Tỉnh Quảng Nam",
    code: "502",
    parent_code: "49",
  },
  {
    label: "Thành phố Hội An",
    path_with_type: "Thành phố Hội An, Tỉnh Quảng Nam",
    code: "503",
    parent_code: "49",
  },
  {
    label: "Huyện Tây Giang",
    code: "504",
    parent_code: "49",
  },
  {
    label: "Huyện Đông Giang",
    code: "505",
    parent_code: "49",
  },
  {
    label: "Huyện Đại Lộc",
    code: "506",
    parent_code: "49",
  },
  {
    label: "Thị xã Điện Bàn",
    path_with_type: "Thị xã Điện Bàn, Tỉnh Quảng Nam",
    code: "507",
    parent_code: "49",
  },
  {
    label: "Huyện Duy Xuyên",
    code: "508",
    parent_code: "49",
  },
  {
    label: "Huyện Quế Sơn",
    code: "509",
    parent_code: "49",
  },
  {
    label: "Huyện Nam Giang",
    code: "510",
    parent_code: "49",
  },
  {
    label: "Huyện Phước Sơn",
    code: "511",
    parent_code: "49",
  },
  {
    label: "Huyện Hiệp Đức",
    code: "512",
    parent_code: "49",
  },
  {
    label: "Huyện Thăng Bình",
    code: "513",
    parent_code: "49",
  },
  {
    label: "Huyện Tiên Phước",
    code: "514",
    parent_code: "49",
  },
  {
    label: "Huyện Bắc Trà My",
    code: "515",
    parent_code: "49",
  },
  {
    label: "Huyện Nam Trà My",
    code: "516",
    parent_code: "49",
  },
  {
    label: "Huyện Núi Thành",
    code: "517",
    parent_code: "49",
  },
  {
    label: "Huyện Phú Ninh",
    code: "518",
    parent_code: "49",
  },
  {
    label: "Huyện Nông Sơn",
    code: "519",
    parent_code: "49",
  },
  {
    label: "Thành phố Buôn Ma Thuột",
    path_with_type: "Thành phố Buôn Ma Thuột, Tỉnh Đắk Lắk",
    code: "643",
    parent_code: "66",
  },
  {
    label: "Thị xã Buôn Hồ",
    path_with_type: "Thị xã Buôn Hồ, Tỉnh Đắk Lắk",
    code: "644",
    parent_code: "66",
  },
  {
    label: "Huyện Ea Hleo",
    code: "645",
    parent_code: "66",
  },
  {
    label: "Huyện Ea Súp",
    code: "646",
    parent_code: "66",
  },
  {
    label: "Huyện Buôn Đôn",
    code: "647",
    parent_code: "66",
  },
  {
    label: "Huyện Cư Mgar",
    code: "648",
    parent_code: "66",
  },
  {
    label: "Huyện Krông Búk",
    code: "649",
    parent_code: "66",
  },
  {
    label: "Huyện Krông Năng",
    code: "650",
    parent_code: "66",
  },
  {
    label: "Huyện Ea Kar",
    code: "651",
    parent_code: "66",
  },
  {
    label: "Huyện MĐrắk",
    code: "652",
    parent_code: "66",
  },
  {
    label: "Huyện Krông Bông",
    code: "653",
    parent_code: "66",
  },
  {
    label: "Huyện Krông Pắc",
    code: "654",
    parent_code: "66",
  },
  {
    label: "Huyện Krông A Na",
    code: "655",
    parent_code: "66",
  },
  {
    label: "Huyện Lắk",
    code: "656",
    parent_code: "66",
  },
  {
    label: "Huyện Cư Kuin",
    code: "657",
    parent_code: "66",
  },
  {
    label: "Thành phố Thái Nguyên",
    path_with_type: "Thành phố Thái Nguyên, Tỉnh Thái Nguyên",
    code: "164",
    parent_code: "19",
  },
  {
    label: "Thành phố Sông Công",
    path_with_type: "Thành phố Sông Công, Tỉnh Thái Nguyên",
    code: "165",
    parent_code: "19",
  },
  {
    label: "Huyện Định Hóa",
    code: "167",
    parent_code: "19",
  },
  {
    label: "Huyện Phú Lương",
    code: "168",
    parent_code: "19",
  },
  {
    label: "Huyện Đồng Hỷ",
    code: "169",
    parent_code: "19",
  },
  {
    label: "Huyện Võ Nhai",
    code: "170",
    parent_code: "19",
  },
  {
    label: "Huyện Đại Từ",
    code: "171",
    parent_code: "19",
  },
  {
    label: "Thị xã Phổ Yên",
    path_with_type: "Thị xã Phổ Yên, Tỉnh Thái Nguyên",
    code: "172",
    parent_code: "19",
  },
  {
    label: "Huyện Phú Bình",
    code: "173",
    parent_code: "19",
  },
  {
    label: "Thành phố Hải Dương",
    path_with_type: "Thành phố Hải Dương, Tỉnh Hải Dương",
    code: "288",
    parent_code: "30",
  },
  {
    label: "Thị xã Chí Linh",
    path_with_type: "Thị xã Chí Linh, Tỉnh Hải Dương",
    code: "290",
    parent_code: "30",
  },
  {
    label: "Huyện Nam Sách",
    code: "291",
    parent_code: "30",
  },
  {
    label: "Huyện Kinh Môn",
    code: "292",
    parent_code: "30",
  },
  {
    label: "Huyện Kim Thành",
    code: "293",
    parent_code: "30",
  },
  {
    label: "Huyện Thanh Hà",
    code: "294",
    parent_code: "30",
  },
  {
    label: "Huyện Cẩm Giàng",
    code: "295",
    parent_code: "30",
  },
  {
    label: "Huyện Bình Giang",
    code: "296",
    parent_code: "30",
  },
  {
    label: "Huyện Gia Lộc",
    code: "297",
    parent_code: "30",
  },
  {
    label: "Huyện Tứ Kỳ",
    code: "298",
    parent_code: "30",
  },
  {
    label: "Huyện Ninh Giang",
    code: "299",
    parent_code: "30",
  },
  {
    label: "Huyện Thanh Miện",
    code: "300",
    parent_code: "30",
  },
  {
    label: "Thành phố Bạc Liêu",
    path_with_type: "Thành phố Bạc Liêu, Tỉnh Bạc Liêu",
    code: "954",
    parent_code: "95",
  },
  {
    label: "Huyện Hồng Dân",
    code: "956",
    parent_code: "95",
  },
  {
    label: "Huyện Phước Long",
    code: "957",
    parent_code: "95",
  },
  {
    label: "Huyện Vĩnh Lợi",
    code: "958",
    parent_code: "95",
  },
  {
    label: "Thị xã Giá Rai",
    path_with_type: "Thị xã Giá Rai, Tỉnh Bạc Liêu",
    code: "959",
    parent_code: "95",
  },
  {
    label: "Huyện Đông Hải",
    code: "960",
    parent_code: "95",
  },
  {
    label: "Huyện Hoà Bình",
    code: "961",
    parent_code: "95",
  },
  {
    label: "Thành phố Trà Vinh",
    path_with_type: "Thành phố Trà Vinh, Tỉnh Trà Vinh",
    code: "842",
    parent_code: "84",
  },
  {
    label: "Huyện Càng Long",
    code: "844",
    parent_code: "84",
  },
  {
    label: "Huyện Cầu Kè",
    code: "845",
    parent_code: "84",
  },
  {
    label: "Huyện Tiểu Cần",
    code: "846",
    parent_code: "84",
  },
  {
    label: "Huyện Châu Thành",
    code: "847",
    parent_code: "84",
  },
  {
    label: "Huyện Cầu Ngang",
    code: "848",
    parent_code: "84",
  },
  {
    label: "Huyện Trà Cú",
    code: "849",
    parent_code: "84",
  },
  {
    label: "Huyện Duyên Hải",
    code: "850",
    parent_code: "84",
  },
  {
    label: "Thị xã Duyên Hải",
    path_with_type: "Thị xã Duyên Hải, Tỉnh Trà Vinh",
    code: "851",
    parent_code: "84",
  },
  {
    label: "Thành phố Thái Bình",
    path_with_type: "Thành phố Thái Bình, Tỉnh Thái Bình",
    code: "336",
    parent_code: "34",
  },
  {
    label: "Huyện Quỳnh Phụ",
    code: "338",
    parent_code: "34",
  },
  {
    label: "Huyện Hưng Hà",
    code: "339",
    parent_code: "34",
  },
  {
    label: "Huyện Đông Hưng",
    code: "340",
    parent_code: "34",
  },
  {
    label: "Huyện Thái Thụy",
    code: "341",
    parent_code: "34",
  },
  {
    label: "Huyện Tiền Hải",
    code: "342",
    parent_code: "34",
  },
  {
    label: "Huyện Kiến Xương",
    code: "343",
    parent_code: "34",
  },
  {
    label: "Huyện Vũ Thư",
    code: "344",
    parent_code: "34",
  },
  {
    label: "Thành phố Hà Tĩnh",
    path_with_type: "Thành phố Hà Tĩnh, Tỉnh Hà Tĩnh",
    code: "436",
    parent_code: "42",
  },
  {
    label: "Thị xã Hồng Lĩnh",
    path_with_type: "Thị xã Hồng Lĩnh, Tỉnh Hà Tĩnh",
    code: "437",
    parent_code: "42",
  },
  {
    label: "Huyện Hương Sơn",
    code: "439",
    parent_code: "42",
  },
  {
    label: "Huyện Đức Thọ",
    code: "440",
    parent_code: "42",
  },
  {
    label: "Huyện Vũ Quang",
    code: "441",
    parent_code: "42",
  },
  {
    label: "Huyện Nghi Xuân",
    code: "442",
    parent_code: "42",
  },
  {
    label: "Huyện Can Lộc",
    code: "443",
    parent_code: "42",
  },
  {
    label: "Huyện Hương Khê",
    code: "444",
    parent_code: "42",
  },
  {
    label: "Huyện Thạch Hà",
    code: "445",
    parent_code: "42",
  },
  {
    label: "Huyện Cẩm Xuyên",
    code: "446",
    parent_code: "42",
  },
  {
    label: "Huyện Kỳ Anh",
    code: "447",
    parent_code: "42",
  },
  {
    label: "Huyện Lộc Hà",
    code: "448",
    parent_code: "42",
  },
  {
    label: "Thị xã Kỳ Anh",
    path_with_type: "Thị xã Kỳ Anh, Tỉnh Hà Tĩnh",
    code: "449",
    parent_code: "42",
  },
  {
    label: "Thành phố Phan Rang-Tháp Chàm",
    path_with_type: "Thành phố Phan Rang-Tháp Chàm, Tỉnh Ninh Thuận",
    code: "582",
    parent_code: "58",
  },
  {
    label: "Huyện Bác Ái",
    code: "584",
    parent_code: "58",
  },
  {
    label: "Huyện Ninh Sơn",
    code: "585",
    parent_code: "58",
  },
  {
    label: "Huyện Ninh Hải",
    code: "586",
    parent_code: "58",
  },
  {
    label: "Huyện Ninh Phước",
    code: "587",
    parent_code: "58",
  },
  {
    label: "Huyện Thuận Bắc",
    code: "588",
    parent_code: "58",
  },
  {
    label: "Huyện Thuận Nam",
    code: "589",
    parent_code: "58",
  },
  {
    label: "Thành phố Cao Lãnh",
    path_with_type: "Thành phố Cao Lãnh, Tỉnh Đồng Tháp",
    code: "866",
    parent_code: "87",
  },
  {
    label: "Thành phố Sa Đéc",
    path_with_type: "Thành phố Sa Đéc, Tỉnh Đồng Tháp",
    code: "867",
    parent_code: "87",
  },
  {
    label: "Thị xã Hồng Ngự",
    path_with_type: "Thị xã Hồng Ngự, Tỉnh Đồng Tháp",
    code: "868",
    parent_code: "87",
  },
  {
    label: "Huyện Tân Hồng",
    code: "869",
    parent_code: "87",
  },
  {
    label: "Huyện Hồng Ngự",
    code: "870",
    parent_code: "87",
  },
  {
    label: "Huyện Tam Nông",
    code: "871",
    parent_code: "87",
  },
  {
    label: "Huyện Tháp Mười",
    code: "872",
    parent_code: "87",
  },
  {
    label: "Huyện Cao Lãnh",
    code: "873",
    parent_code: "87",
  },
  {
    label: "Huyện Thanh Bình",
    code: "874",
    parent_code: "87",
  },
  {
    label: "Huyện Lấp Vò",
    code: "875",
    parent_code: "87",
  },
  {
    label: "Huyện Lai Vung",
    code: "876",
    parent_code: "87",
  },
  {
    label: "Huyện Châu Thành",
    code: "877",
    parent_code: "87",
  },
  {
    label: "Thành phố Tân An",
    path_with_type: "Thành phố Tân An, Tỉnh Long An",
    code: "794",
    parent_code: "80",
  },
  {
    label: "Thị xã Kiến Tường",
    path_with_type: "Thị xã Kiến Tường, Tỉnh Long An",
    code: "795",
    parent_code: "80",
  },
  {
    label: "Huyện Tân Hưng",
    code: "796",
    parent_code: "80",
  },
  {
    label: "Huyện Vĩnh Hưng",
    code: "797",
    parent_code: "80",
  },
  {
    label: "Huyện Mộc Hóa",
    code: "798",
    parent_code: "80",
  },
  {
    label: "Huyện Tân Thạnh",
    code: "799",
    parent_code: "80",
  },
  {
    label: "Huyện Thạnh Hóa",
    code: "800",
    parent_code: "80",
  },
  {
    label: "Huyện Đức Huệ",
    code: "801",
    parent_code: "80",
  },
  {
    label: "Huyện Đức Hòa",
    code: "802",
    parent_code: "80",
  },
  {
    label: "Huyện Bến Lức",
    code: "803",
    parent_code: "80",
  },
  {
    label: "Huyện Thủ Thừa",
    code: "804",
    parent_code: "80",
  },
  {
    label: "Huyện Tân Trụ",
    code: "805",
    parent_code: "80",
  },
  {
    label: "Huyện Cần Đước",
    code: "806",
    parent_code: "80",
  },
  {
    label: "Huyện Cần Giuộc",
    code: "807",
    parent_code: "80",
  },
  {
    label: "Huyện Châu Thành",
    code: "808",
    parent_code: "80",
  },
  {
    label: "Thành phố Vị Thanh",
    path_with_type: "Thành phố Vị Thanh, Tỉnh Hậu Giang",
    code: "930",
    parent_code: "93",
  },
  {
    label: "Thị xã Ngã Bảy",
    path_with_type: "Thị xã Ngã Bảy, Tỉnh Hậu Giang",
    code: "931",
    parent_code: "93",
  },
  {
    label: "Huyện Châu Thành A",
    code: "932",
    parent_code: "93",
  },
  {
    label: "Huyện Châu Thành",
    code: "933",
    parent_code: "93",
  },
  {
    label: "Huyện Phụng Hiệp",
    code: "934",
    parent_code: "93",
  },
  {
    label: "Huyện Vị Thuỷ",
    code: "935",
    parent_code: "93",
  },
  {
    label: "Huyện Long Mỹ",
    code: "936",
    parent_code: "93",
  },
  {
    label: "Thị xã Long Mỹ",
    path_with_type: "Thị xã Long Mỹ, Tỉnh Hậu Giang",
    code: "937",
    parent_code: "93",
  },
  {
    label: "Thành phố Hạ Long",
    path_with_type: "Thành phố Hạ Long, Tỉnh Quảng Ninh",
    code: "193",
    parent_code: "22",
  },
  {
    label: "Thành phố Móng Cái",
    path_with_type: "Thành phố Móng Cái, Tỉnh Quảng Ninh",
    code: "194",
    parent_code: "22",
  },
  {
    label: "Thành phố Cẩm Phả",
    path_with_type: "Thành phố Cẩm Phả, Tỉnh Quảng Ninh",
    code: "195",
    parent_code: "22",
  },
  {
    label: "Thành phố Uông Bí",
    path_with_type: "Thành phố Uông Bí, Tỉnh Quảng Ninh",
    code: "196",
    parent_code: "22",
  },
  {
    label: "Huyện Bình Liêu",
    code: "198",
    parent_code: "22",
  },
  {
    label: "Huyện Tiên Yên",
    code: "199",
    parent_code: "22",
  },
  {
    label: "Huyện Đầm Hà",
    code: "200",
    parent_code: "22",
  },
  {
    label: "Huyện Hải Hà",
    code: "201",
    parent_code: "22",
  },
  {
    label: "Huyện Ba Chẽ",
    code: "202",
    parent_code: "22",
  },
  {
    label: "Huyện Vân Đồn",
    code: "203",
    parent_code: "22",
  },
  {
    label: "Huyện Hoành Bồ",
    code: "204",
    parent_code: "22",
  },
  {
    label: "Thị xã Đông Triều",
    path_with_type: "Thị xã Đông Triều, Tỉnh Quảng Ninh",
    code: "205",
    parent_code: "22",
  },
  {
    label: "Thị xã Quảng Yên",
    path_with_type: "Thị xã Quảng Yên, Tỉnh Quảng Ninh",
    code: "206",
    parent_code: "22",
  },
  {
    label: "Huyện Cô Tô",
    code: "207",
    parent_code: "22",
  },
  {
    label: "Thành phố Việt Trì",
    path_with_type: "Thành phố Việt Trì, Tỉnh Phú Thọ",
    code: "227",
    parent_code: "25",
  },
  {
    label: "Thị xã Phú Thọ",
    path_with_type: "Thị xã Phú Thọ, Tỉnh Phú Thọ",
    code: "228",
    parent_code: "25",
  },
  {
    label: "Huyện Đoan Hùng",
    code: "230",
    parent_code: "25",
  },
  {
    label: "Huyện Hạ Hoà",
    code: "231",
    parent_code: "25",
  },
  {
    label: "Huyện Thanh Ba",
    code: "232",
    parent_code: "25",
  },
  {
    label: "Huyện Phù Ninh",
    code: "233",
    parent_code: "25",
  },
  {
    label: "Huyện Yên Lập",
    code: "234",
    parent_code: "25",
  },
  {
    label: "Huyện Cẩm Khê",
    code: "235",
    parent_code: "25",
  },
  {
    label: "Huyện Tam Nông",
    code: "236",
    parent_code: "25",
  },
  {
    label: "Huyện Lâm Thao",
    code: "237",
    parent_code: "25",
  },
  {
    label: "Huyện Thanh Sơn",
    code: "238",
    parent_code: "25",
  },
  {
    label: "Huyện Thanh Thuỷ",
    code: "239",
    parent_code: "25",
  },
  {
    label: "Huyện Tân Sơn",
    code: "240",
    parent_code: "25",
  },
  {
    label: "Thành Phố Đồng Hới",
    path_with_type: "Thành Phố Đồng Hới, Tỉnh Quảng Bình",
    code: "450",
    parent_code: "44",
  },
  {
    label: "Huyện Minh Hóa",
    code: "452",
    parent_code: "44",
  },
  {
    label: "Huyện Tuyên Hóa",
    code: "453",
    parent_code: "44",
  },
  {
    label: "Huyện Quảng Trạch",
    code: "454",
    parent_code: "44",
  },
  {
    label: "Huyện Bố Trạch",
    code: "455",
    parent_code: "44",
  },
  {
    label: "Huyện Quảng Ninh",
    code: "456",
    parent_code: "44",
  },
  {
    label: "Huyện Lệ Thủy",
    code: "457",
    parent_code: "44",
  },
  {
    label: "Thị xã Ba Đồn",
    path_with_type: "Thị xã Ba Đồn, Tỉnh Quảng Bình",
    code: "458",
    parent_code: "44",
  },
  {
    label: "Quận 1",
    path_with_type: "Quận 1, Thành phố Hồ Chí Minh",
    code: "760",
    parent_code: "79",
  },
  {
    label: "Quận 12",
    path_with_type: "Quận 12, Thành phố Hồ Chí Minh",
    code: "761",
    parent_code: "79",
  },
  {
    label: "Quận Thủ Đức",
    path_with_type: "Quận Thủ Đức, Thành phố Hồ Chí Minh",
    code: "762",
    parent_code: "79",
  },
  {
    label: "Quận 9",
    path_with_type: "Quận 9, Thành phố Hồ Chí Minh",
    code: "763",
    parent_code: "79",
  },
  {
    label: "Quận Gò Vấp",
    path_with_type: "Quận Gò Vấp, Thành phố Hồ Chí Minh",
    code: "764",
    parent_code: "79",
  },
  {
    label: "Quận Bình Thạnh",
    path_with_type: "Quận Bình Thạnh, Thành phố Hồ Chí Minh",
    code: "765",
    parent_code: "79",
  },
  {
    label: "Quận Tân Bình",
    path_with_type: "Quận Tân Bình, Thành phố Hồ Chí Minh",
    code: "766",
    parent_code: "79",
  },
  {
    label: "Quận Tân Phú",
    path_with_type: "Quận Tân Phú, Thành phố Hồ Chí Minh",
    code: "767",
    parent_code: "79",
  },
  {
    label: "Quận Phú Nhuận",
    path_with_type: "Quận Phú Nhuận, Thành phố Hồ Chí Minh",
    code: "768",
    parent_code: "79",
  },
  {
    label: "Quận 2",
    path_with_type: "Quận 2, Thành phố Hồ Chí Minh",
    code: "769",
    parent_code: "79",
  },
  {
    label: "Quận 3",
    path_with_type: "Quận 3, Thành phố Hồ Chí Minh",
    code: "770",
    parent_code: "79",
  },
  {
    label: "Quận 10",
    path_with_type: "Quận 10, Thành phố Hồ Chí Minh",
    code: "771",
    parent_code: "79",
  },
  {
    label: "Quận 11",
    path_with_type: "Quận 11, Thành phố Hồ Chí Minh",
    code: "772",
    parent_code: "79",
  },
  {
    label: "Quận 4",
    path_with_type: "Quận 4, Thành phố Hồ Chí Minh",
    code: "773",
    parent_code: "79",
  },
  {
    label: "Quận 5",
    path_with_type: "Quận 5, Thành phố Hồ Chí Minh",
    code: "774",
    parent_code: "79",
  },
  {
    label: "Quận 6",
    path_with_type: "Quận 6, Thành phố Hồ Chí Minh",
    code: "775",
    parent_code: "79",
  },
  {
    label: "Quận 8",
    path_with_type: "Quận 8, Thành phố Hồ Chí Minh",
    code: "776",
    parent_code: "79",
  },
  {
    label: "Quận Bình Tân",
    path_with_type: "Quận Bình Tân, Thành phố Hồ Chí Minh",
    code: "777",
    parent_code: "79",
  },
  {
    label: "Quận 7",
    path_with_type: "Quận 7, Thành phố Hồ Chí Minh",
    code: "778",
    parent_code: "79",
  },
  {
    label: "Huyện Củ Chi",
    code: "783",
    parent_code: "79",
  },
  {
    label: "Huyện Hóc Môn",
    code: "784",
    parent_code: "79",
  },
  {
    label: "Huyện Bình Chánh",
    code: "785",
    parent_code: "79",
  },
  {
    label: "Huyện Nhà Bè",
    code: "786",
    parent_code: "79",
  },
  {
    label: "Huyện Cần Giờ",
    code: "787",
    parent_code: "79",
  },
  {
    label: "Thành phố Phủ Lý",
    path_with_type: "Thành phố Phủ Lý, Tỉnh Hà Nam",
    code: "347",
    parent_code: "35",
  },
  {
    label: "Huyện Duy Tiên",
    code: "349",
    parent_code: "35",
  },
  {
    label: "Huyện Kim Bảng",
    code: "350",
    parent_code: "35",
  },
  {
    label: "Huyện Thanh Liêm",
    code: "351",
    parent_code: "35",
  },
  {
    label: "Huyện Bình Lục",
    code: "352",
    parent_code: "35",
  },
  {
    label: "Huyện Lý Nhân",
    code: "353",
    parent_code: "35",
  },
  {
    label: "Thành phố Bắc Ninh",
    path_with_type: "Thành phố Bắc Ninh, Tỉnh Bắc Ninh",
    code: "256",
    parent_code: "27",
  },
  {
    label: "Huyện Yên Phong",
    code: "258",
    parent_code: "27",
  },
  {
    label: "Huyện Quế Võ",
    code: "259",
    parent_code: "27",
  },
  {
    label: "Huyện Tiên Du",
    code: "260",
    parent_code: "27",
  },
  {
    label: "Thị xã Từ Sơn",
    path_with_type: "Thị xã Từ Sơn, Tỉnh Bắc Ninh",
    code: "261",
    parent_code: "27",
  },
  {
    label: "Huyện Thuận Thành",
    code: "262",
    parent_code: "27",
  },
  {
    label: "Huyện Gia Bình",
    code: "263",
    parent_code: "27",
  },
  {
    label: "Huyện Lương Tài",
    code: "264",
    parent_code: "27",
  },
  {
    label: "Thành phố Bắc Giang",
    path_with_type: "Thành phố Bắc Giang, Tỉnh Bắc Giang",
    code: "213",
    parent_code: "24",
  },
  {
    label: "Huyện Yên Thế",
    code: "215",
    parent_code: "24",
  },
  {
    label: "Huyện Tân Yên",
    code: "216",
    parent_code: "24",
  },
  {
    label: "Huyện Lạng Giang",
    code: "217",
    parent_code: "24",
  },
  {
    label: "Huyện Lục Nam",
    code: "218",
    parent_code: "24",
  },
  {
    label: "Huyện Lục Ngạn",
    code: "219",
    parent_code: "24",
  },
  {
    label: "Huyện Sơn Động",
    code: "220",
    parent_code: "24",
  },
  {
    label: "Huyện Yên Dũng",
    code: "221",
    parent_code: "24",
  },
  {
    label: "Huyện Việt Yên",
    code: "222",
    parent_code: "24",
  },
  {
    label: "Huyện Hiệp Hòa",
    code: "223",
    parent_code: "24",
  },
  {
    label: "Thành Phố Bắc Kạn",
    path_with_type: "Thành Phố Bắc Kạn, Tỉnh Bắc Kạn",
    code: "058",
    parent_code: "06",
  },
  {
    label: "Huyện Pác Nặm",
    code: "060",
    parent_code: "06",
  },
  {
    label: "Huyện Ba Bể",
    code: "061",
    parent_code: "06",
  },
  {
    label: "Huyện Ngân Sơn",
    code: "062",
    parent_code: "06",
  },
  {
    label: "Huyện Bạch Thông",
    code: "063",
    parent_code: "06",
  },
  {
    label: "Huyện Chợ Đồn",
    code: "064",
    parent_code: "06",
  },
  {
    label: "Huyện Chợ Mới",
    code: "065",
    parent_code: "06",
  },
  {
    label: "Huyện Na Rì",
    code: "066",
    parent_code: "06",
  },
];
